FROM node
WORKDIR /avengers-frontend
ENV PATH /avengers-frontend/node_modules/.bin:$PATH
COPY package*.json ./

RUN npm install --silent
RUN npm install react-scripts -g --silent

COPY . . 
# EXPOSE 3000
CMD ["npm", "start"]
